<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20170420110058 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE onedrop_restrictedfiles_domain_model_downloadcount DROP FOREIGN KEY FK_820A58367D3656A4');
        $this->addSql('ALTER TABLE onedrop_restrictedfiles_domain_model_downloadcount DROP FOREIGN KEY FK_820A5836BC91F416');
        $this->addSql('ALTER TABLE onedrop_restrictedfiles_domain_model_downloadcount ADD CONSTRAINT FK_820A58367D3656A4 FOREIGN KEY (account) REFERENCES neos_flow_security_account (persistence_object_identifier) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE onedrop_restrictedfiles_domain_model_downloadcount ADD CONSTRAINT FK_820A5836BC91F416 FOREIGN KEY (resource) REFERENCES neos_flow_resourcemanagement_persistentresource (persistence_object_identifier) ON DELETE SET NULL');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE onedrop_restrictedfiles_domain_model_downloadcount DROP FOREIGN KEY FK_820A5836BC91F416');
        $this->addSql('ALTER TABLE onedrop_restrictedfiles_domain_model_downloadcount DROP FOREIGN KEY FK_820A58367D3656A4');
        $this->addSql('ALTER TABLE onedrop_restrictedfiles_domain_model_downloadcount ADD CONSTRAINT FK_820A5836BC91F416 FOREIGN KEY (resource) REFERENCES neos_flow_resourcemanagement_persistentresource (persistence_object_identifier)');
        $this->addSql('ALTER TABLE onedrop_restrictedfiles_domain_model_downloadcount ADD CONSTRAINT FK_820A58367D3656A4 FOREIGN KEY (account) REFERENCES neos_flow_security_account (persistence_object_identifier)');
    }
}
